tidy files

diff --git a/.github/workflows/clang-tidy-automotive.yml b/.github/workflows/clang-tidy-automotive.yml
--- a/.github/workflows/clang-tidy-automotive.yml
+++ b/.github/workflows/clang-tidy-automotive.yml
@@ -52,13 +52,54 @@ jobs:
       - name: clang-tidy checking
         shell: bash
         run: |
-              CLANG_TIDY="/opt/clang-tidy-automotive/build/bin/clang-tidy"
-              BSP_SERIES=$(ls $GITHUB_WORKSPACE/Library/Device/Nuvoton/ | head -n 1)
-              INCLUDE_PATHS="-I $GITHUB_WORKSPACE/Library/CMSIS/Core/Include/ -I $GITHUB_WORKSPACE/Library/Device/Nuvoton/$BSP_SERIES/Include/ -I $GITHUB_WORKSPACE/Library/StdDriver/inc/"
+          CLANG_TIDY_AUTOMOTIVE="/opt/clang-tidy-automotive/"
+          CLANG_TIDY_BIN="/opt/clang-tidy-automotive/build/bin/clang-tidy"
+          BSP_SERIES=$(ls $GITHUB_WORKSPACE/Library/Device/Nuvoton/ | head -n 1)
+          INCLUDE_PATHS="-I $GITHUB_WORKSPACE/Library/CMSIS/Core/Include/ -I $GITHUB_WORKSPACE/Library/Device/Nuvoton/$BSP_SERIES/Include/ -I $GITHUB_WORKSPACE/Library/StdDriver/inc/"
 
-              echo "🧩 BSP_SERIES=$BSP_SERIES"
-              cd $GITHUB_WORKSPACE
-              find Library -type f -name "*.c" | while read -r file; do
-                $CLANG_TIDY --checks="automotive-*" "$file" -- $INCLUDE_PATHS
-              done
+          cd $GITHUB_WORKSPACE
+          mapfile -t solutions < <(find ./Library/StdDriver/src -name '*.c')
+          declare -a failed_logs=()
 
+          echo "🧩 BSP_SERIES=$BSP_SERIES"
+          cd $CLANG_TIDY_AUTOMOTIVE
+
+          set +e
+          for file_path in "${solutions[@]}"; do
+
+            dir=$(dirname "$file_path")
+            sol_name=$(basename "$file_path")
+            log_path="$dir/$sol_name.clang-tidy-automotive.log"
+
+            $CLANG_TIDY_BIN --checks="automotive-*" \
+                            --header-filter='.*' \
+                            --quiet \
+                            "$file_path" \
+                            -- \
+                            $INCLUDE_PATHS > log_path
+            ret=$?
+
+            if [[ $ret -ne 0 ]]; then
+              echo "❌ Clang-tidy failed: $sol_path"
+              echo "🔍 Log:"
+              cat "$log_path"
+
+              failed_logs+=("$log_path")   # add log into the set
+            fi
+
+          done
+
+          set -e
+
+          # List all the paths of failed logs at the end (if any)
+          if [[ ${#failed_logs[@]} -ne 0 ]]; then
+            echo "🚨 The following builds failed:"
+            for log in "${failed_logs[@]}"; do
+              echo "  - $log"
+            done
+            printf "%s," "${failed_logs[@]}" | sed 's/,$//' > "$GITHUB_WORKSPACE/failed_logs.txt"
+            echo "Wrote failed_logs.txt"
+            exit 1
+          else
+            echo "🎉 All check succeeded!"
+          fi
