fix

diff --git a/.github/workflows/IAR_GithubHosted.yml b/.github/workflows/IAR_GithubHosted.yml
--- a/.github/workflows/IAR_GithubHosted.yml
+++ b/.github/workflows/IAR_GithubHosted.yml
@@ -1,10 +1,10 @@
 name: IAR GH Runner building 
 
 on:
-  push:
-    branches-ignore:
-      - main
-      - master
+  #push:
+  #  branches-ignore:
+  #    - main
+  #    - master
   #pull_request:
   #  branches-ignore:
   #    - main
@@ -18,7 +18,7 @@ env:
   IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}
 
 jobs:
-  build:
+  build-project:
     name: Build project
     runs-on: ubuntu-latest
     container: ghcr.io/iarsystems/arm:9.60.4-st
@@ -63,7 +63,7 @@ jobs:
           REPO_ROOT="$GITHUB_WORKSPACE"
           chmod +x "$GITHUB_WORKSPACE/.github/workflows/vcpkg_blacklist_check.sh"
 
-          mapfile -t solutions < <(find ./SampleCode -name '*.ewp')
+          mapfile -t solutions < <(find ./SampleCode/Template -name '*.ewp')
           declare -a failed_logs=()
 
           set +e
@@ -164,3 +164,47 @@ jobs:
         with:
           name: firmware-artifacts
           path: artifacts/
+
+  cstat-project:
+    name: Static Code Analysis
+    needs: build-project
+    runs-on: ubuntu-latest
+    container: ghcr.io/iarsystems/arm:9.60.4-st
+    steps:
+      - uses: actions/checkout@v4
+      - name: Static Analysis
+        shell: bash
+        run: |
+          mapfile -t solutions < <(find ./SampleCode/Template -name '*.ewp')
+          declare -a failed_logs=()
+
+          set +e
+          for sol_path in "${solutions[@]}"; do
+
+            dir=$(dirname "$sol_path")
+            sol_name=$(basename "$sol_path")
+            log_path="$dir/$sol_name.cstat.log"
+
+            iarbuild $sol_path -cstat_analyze '*' -log all > $log_path
+            ret1=$?
+
+            iarbuild $sol_path -cstat_report '*' -log all >> $log_path
+            ret2=$?
+
+            if [[ $ret1 -ne 0 || $ret2 -ne 0 ]]; then
+              echo "❌ Build failed: $sol_path"
+              echo "🔍 Log:"
+              cat "$log_path"
+            else
+              echo "✅ Analysis success: $sol_path"
+            fi
+
+          done
+          set -e
+
+      - name: Upload project report (C-STAT)
+        uses: actions/upload-artifact@v4
+        with:
+          name: all-cstat.html
+          path: SampleCode/**/C-STAT/*.html
+          if-no-files-found: error
